const DB_SEED_DATA = [
  {
    cluster_id: 'story-hero-1',
    created_at: new Date().toISOString(),
    updated_at: '7m read',
    topic_label: 'Trump’s Government Efficiency Department Disbands Eight Months Before Mandate Ends',
    topic_keywords: JSON.stringify(['Elon Musk', 'Vivek Ramaswamy', 'DOGE', 'Government Efficiency']),
    representative_embedding: JSON.stringify([0.5, 0.1, -0.2]),
    summary: 'The Department of Government Efficiency, led by Elon Musk and Vivek Ramaswamy, is winding down operations earlier than expected.',
    bias_distribution: JSON.stringify({ left: 42, center: 19, right: 39 }),
    source_count: 394,
    language_distribution: JSON.stringify({ en: 100 }),
    is_active: 1,
    ai_summary: JSON.stringify(['DOGE to shut down 8 months early.', 'Musk claims mission accomplished.', 'Critics argue substantial waste remains.']),
    category: 'US Politics',
    blindspot: null,
    image_url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1632&q=80',
    source_ids: ['the-hindu', 'ndtv', 'republic-world', 'opindia']
  },
  {
    cluster_id: 'story-1',
    created_at: new Date().toISOString(),
    updated_at: '2 hours ago',
    topic_label: 'Israel Strikes Hezbollah Chief in First Beirut Attack Since June',
    topic_keywords: JSON.stringify(['Hezbollah', 'Beirut', 'Israel', 'Ali Tabtabai']),
    representative_embedding: JSON.stringify([0.8, -0.2, 0.1]),
    summary: 'Israel\'s first strike on Beirut since June hit Haret Hreik, targeting Hezbollah chief of staff Ali Tabtabai.',
    bias_distribution: JSON.stringify({ left: 45, center: 10, right: 45 }),
    source_count: 45,
    language_distribution: JSON.stringify({ en: 90, hi: 10 }),
    is_active: 1,
    ai_summary: JSON.stringify(['Targeted strike in Beirut suburbs.', 'At least five killed, 28 wounded.', 'Escalation in Israel-Hezbollah conflict.']),
    category: 'Israel-Gaza',
    blindspot: null,
    image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    source_ids: ['the-wire', 'scroll', 'ndtv', 'republic-world', 'times-of-india']
  },
  {
    cluster_id: 'story-2',
    created_at: new Date().toISOString(),
    updated_at: '5 hours ago',
    topic_label: 'No recession risk for US economy as a whole after $11 billion shutdown hit, Bessent says',
    topic_keywords: JSON.stringify(['Scott Bessent', 'US Economy', 'Recession', 'Shutdown']),
    representative_embedding: JSON.stringify([0.1, 0.3, 0.5]),
    summary: 'Treasury Secretary Scott Bessent assures the public that the recent government shutdown will not trigger a recession.',
    bias_distribution: JSON.stringify({ left: 20, center: 56, right: 24 }),
    source_count: 9,
    language_distribution: JSON.stringify({ en: 100 }),
    is_active: 1,
    ai_summary: JSON.stringify(['Shutdown cost estimated at $11 billion.', 'Economy remains resilient.', 'Inflation cooling down.']),
    category: 'Business & Markets',
    blindspot: null,
    image_url: 'https://images.unsplash.com/photo-1526304640152-d4619684e484?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    source_ids: ['the-hindu', 'ndtv', 'indian-express']
  },
  {
    cluster_id: 'story-3',
    created_at: new Date().toISOString(),
    updated_at: '1 day ago',
    topic_label: 'Rep. Marjorie Taylor Greene to Resign from US Congress After Fallout with Trump',
    topic_keywords: JSON.stringify(['Marjorie Taylor Greene', 'Donald Trump', 'Congress', 'Resignation']),
    representative_embedding: JSON.stringify([-0.2, 0.4, 0.4]),
    summary: 'MTG announces resignation following a public disagreement with former President Trump over policy direction.',
    bias_distribution: JSON.stringify({ left: 25, center: 45, right: 30 }),
    source_count: 355,
    language_distribution: JSON.stringify({ en: 100 }),
    is_active: 0,
    ai_summary: JSON.stringify(['Resignation effective next month.', 'Cites irreconcilable differences.', 'Speculation on future political career.']),
    category: 'US Politics',
    blindspot: null,
    image_url: 'https://images.unsplash.com/photo-1555848962-6e79363ec58f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    source_ids: ['the-wire', 'republic-world']
  },
  {
    cluster_id: 'story-4',
    created_at: new Date().toISOString(),
    updated_at: '30 mins ago',
    topic_label: 'Zelenskyy says Ukraine is grateful for efforts by US, Trump',
    topic_keywords: JSON.stringify(['Zelenskyy', 'Ukraine', 'Trump', 'US Aid']),
    representative_embedding: JSON.stringify([0.1, 0.1, 0.1]),
    summary: 'Ukrainian President expresses gratitude for continued support amidst changing US political landscape.',
    bias_distribution: JSON.stringify({ left: 30, center: 30, right: 40 }),
    source_count: 10,
    language_distribution: JSON.stringify({ en: 100 }),
    is_active: 1,
    ai_summary: JSON.stringify(['Zelenskyy meets US officials.', 'Discusses future aid packages.', 'Emphasizes bipartisan support.']),
    category: 'Ukraine War',
    blindspot: 'Right',
    image_url: 'https://images.unsplash.com/photo-1605152276897-4f618f831968?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    source_ids: ['the-hindu', 'ndtv', 'republic-world']
  },
  {
    cluster_id: 'story-5',
    created_at: new Date().toISOString(),
    updated_at: '1 day ago',
    topic_label: 'US Set to Label Muslim Brotherhood a Foreign Terrorist Organization: Report',
    topic_keywords: JSON.stringify(['Muslim Brotherhood', 'US State Dept', 'Terrorism', 'Foreign Policy']),
    representative_embedding: JSON.stringify([0.9, 0.1, 0.0]),
    summary: 'Reports indicate the administration is moving to designate the Muslim Brotherhood as a terrorist organization.',
    bias_distribution: JSON.stringify({ left: 0, center: 0, right: 100 }),
    source_count: 120,
    language_distribution: JSON.stringify({ en: 100 }),
    is_active: 1,
    ai_summary: JSON.stringify(['Move debated for years.', 'Potential diplomatic fallout.', 'Support from certain allies.']),
    category: 'World',
    blindspot: 'Left',
    image_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    source_ids: ['republic-world', 'opindia']
  },
  {
    cluster_id: 'story-6',
    created_at: new Date().toISOString(),
    updated_at: '2 days ago',
    topic_label: 'Daughter of Holocaust Survivor Among Those Arrested at Palestine Action Protest',
    topic_keywords: JSON.stringify(['Palestine Action', 'Protest', 'Holocaust Survivor', 'Defense Manufacturing']),
    representative_embedding: JSON.stringify([-0.5, -0.5, 0.0]),
    summary: 'Protests at a defense manufacturing facility led to several arrests, including descendants of Holocaust survivors.',
    bias_distribution: JSON.stringify({ left: 46, center: 45, right: 9 }),
    source_count: 45,
    language_distribution: JSON.stringify({ en: 100 }),
    is_active: 1,
    ai_summary: JSON.stringify(['Protestors blocked factory entrance.', 'Police arrested 12 individuals.', 'Activists claim factory supplies IDF.']),
    category: 'Israel-Gaza',
    blindspot: 'Right',
    image_url: 'https://images.unsplash.com/photo-1555848962-6e79363ec58f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    source_ids: ['the-wire', 'scroll', 'ndtv']
  }
];

module.exports = { DB_SEED_DATA };
